// Created by iWeb 3.0.4 local-build-20121226

setTransparentGifURL('../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'Availability_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Availability_files/stroke_17.png'},{rect:new IWRect(2,-2,56,4),url:'Availability_files/stroke_18.png'},{rect:new IWRect(58,-2,4,4),url:'Availability_files/stroke_19.png'},{rect:new IWRect(58,2,4,56),url:'Availability_files/stroke_20.png'},{rect:new IWRect(58,58,4,4),url:'Availability_files/stroke_21.png'},{rect:new IWRect(2,58,56,4),url:'Availability_files/stroke_22.png'},{rect:new IWRect(-2,58,4,4),url:'Availability_files/stroke_23.png'}],new IWSize(60,60)),shadow_2:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'Availability_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Availability_files/stroke_9.png'},{rect:new IWRect(2,-2,56,4),url:'Availability_files/stroke_10.png'},{rect:new IWRect(58,-2,4,4),url:'Availability_files/stroke_11.png'},{rect:new IWRect(58,2,4,56),url:'Availability_files/stroke_12.png'},{rect:new IWRect(58,58,4,4),url:'Availability_files/stroke_13.png'},{rect:new IWRect(2,58,56,4),url:'Availability_files/stroke_14.png'},{rect:new IWRect(-2,58,4,4),url:'Availability_files/stroke_15.png'}],new IWSize(60,60)),shadow_1:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),shadow_3:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),shadow_0:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'Availability_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Availability_files/stroke_1.png'},{rect:new IWRect(2,-2,56,4),url:'Availability_files/stroke_2.png'},{rect:new IWRect(58,-2,4,4),url:'Availability_files/stroke_3.png'},{rect:new IWRect(58,2,4,56),url:'Availability_files/stroke_4.png'},{rect:new IWRect(58,58,4,4),url:'Availability_files/stroke_5.png'},{rect:new IWRect(2,58,56,4),url:'Availability_files/stroke_6.png'},{rect:new IWRect(-2,58,4,4),url:'Availability_files/stroke_7.png'}],new IWSize(60,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function photocastSubscribe()
{photocastHelper("http://www.newstarproperties.ca/Availability/rss.xml");}
function onPageLoad()
{loadMozillaCSS('Availability_files/AvailabilityMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');detectBrowser();fixAllIEPNGs('../Media/transparent.gif');fixupAllIEPNGBGs();Widget.onload();fixupIECSS3Opacity('id6');applyEffects()}
function onPageUnload()
{Widget.onunload();}
